package TP2;

import static org.junit.Assert.*;

import org.junit.Test;

public class PathFinderTest {

	@Test
	public void GIVEN_pathFinder_WHEN_IsaskedToResolveUpperLinearPathMaze_THEN_MazeIsResolve() {
		
		//Arrange
		IPathFinder pathfinder = new PathFinderCounterClockwise();
		
		final String FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String SECOND_ROW = 		"XXXXXXXXXEXXXXXXXXXX";
		final String THIRD_ROW = 		"XXXXXXXXX XXXXXXXXXX";
		final String FOURTH_ROW = 		"XXXXXXXXX XXXXXXXXXX";
		final String FIFTH_ROW = 		"XXXXXXXXX XXXXXXXXXX";
		final String SIXTH_ROW = 		"XXXXXXXXXSXXXXXXXXXX";
		final String SEVENTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EIGHTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String NINETH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String TENTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String ELEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String TWELVETH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String THIRTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String FOURTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String FIVETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String SEVENTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		
		final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHTH_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRTEENTH_ROW + FOURTEENTH_ROW + FIVETEENTH_ROW + SIXTHEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;  
		
		//Act
		
		String newMaze = pathfinder.pathToExit(MAZE);
		
		//Assert
		final String EXPECTED_FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SECOND_ROW = 		"XXXXXXXXXEXXXXXXXXXX";
		final String EXPECTED_THIRD_ROW = 		"XXXXXXXXXPXXXXXXXXXX";
		final String EXPECTED_FOURTH_ROW = 		"XXXXXXXXXPXXXXXXXXXX";
		final String EXPECTED_FIFTH_ROW = 		"XXXXXXXXXPXXXXXXXXXX";
		final String EXPECTED_SIXTH_ROW = 		"XXXXXXXXXSXXXXXXXXXX";
		final String EXPECTED_SEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_EIGHTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_NINETH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_TENTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_ELEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_TWELVETH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_THIRTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_FOURTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_FIVETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SEVENTEENTH_ROW = "XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		
		final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHTH_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIVETEENTH_ROW + EXPECTED_SIXTHEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;
		final String ACTUAL_MAZE = newMaze;
		assertEquals(EXPECTED_MAZE,ACTUAL_MAZE);
	}
	
	@Test
	public void GIVEN_pathFinder_WHEN_IsaskedToResolveRightLinearPathMaze_THEN_MazeIsResolve() {
		
		//Arrange
		IPathFinder pathfinder = new PathFinderCounterClockwise();
		
		final String FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String SECOND_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String THIRD_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String FOURTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String FIFTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String SIXTH_ROW = 		"XXXXXXXXXS    EXXXXX";
		final String SEVENTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EIGHTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String NINETH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String TENTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String ELEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String TWELVETH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String THIRTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String FOURTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String FIVETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String SEVENTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		
		final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHTH_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRTEENTH_ROW + FOURTEENTH_ROW + FIVETEENTH_ROW + SIXTHEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;  
		
		//Act
		
		String newMaze = pathfinder.pathToExit(MAZE);
		
		//Assert
		final String EXPECTED_FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SECOND_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_THIRD_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_FOURTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_FIFTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SIXTH_ROW = 		"XXXXXXXXXSPPPPEXXXXX";
		final String EXPECTED_SEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_EIGHTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_NINETH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
	    final String EXPECTED_TENTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_ELEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_TWELVETH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_THIRTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_FOURTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_FIVETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SEVENTEENTH_ROW = "XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		
		final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHTH_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIVETEENTH_ROW + EXPECTED_SIXTHEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;
		final String ACTUAL_MAZE = newMaze;
		assertEquals(EXPECTED_MAZE,ACTUAL_MAZE);
	}
	
	@Test
    public void GIVEN_PathFinder_WHEN_PathFinderIsAskedToResolveALeftLinearMaze_THEN_mazeIsResolved(){
		//Arrange
	    final String FIRST_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String SECOND_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String THIRD_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String FOURTH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String FIFTH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String SIXTH_ROW =         	"XXXXE    SXXXXXXXXXX";
	    final String SEVENTH_ROW =        	"XXXXXXXXXXXXXXXXXXXX";
	    final String EIGHT_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String NINETH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String TENTH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String ELEVENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String TWELVETH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String THIRDTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String FOURTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String FIFTHEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String SIXTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String SEVENTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String EIGHTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String NINETEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String TWENTYTH_ROW =    		"XXXXXXXXXXXXXXXXXXXX";
	
	    final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHT_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRDTEENTH_ROW + FOURTEENTH_ROW + FIFTHEENTH_ROW + SIXTEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;
	
	    IPathFinder pathfinder = new PathFinderCounterClockwise();
	    
    	//Act
	
  		String newMaze = pathfinder.pathToExit(MAZE);
  		
  		//Assert
  		final String EXPECTED_FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SECOND_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_THIRD_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FOURTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FIFTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SIXTH_ROW = 		"XXXXEPPPPSXXXXXXXXXX";
  		final String EXPECTED_SEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_EIGHTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_NINETH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TENTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_ELEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TWELVETH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_THIRTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FOURTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FIVETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SEVENTEENTH_ROW = "XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		
  		final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHTH_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIVETEENTH_ROW + EXPECTED_SIXTHEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;
  		final String ACTUAL_MAZE = newMaze;
  		assertEquals(EXPECTED_MAZE,ACTUAL_MAZE);
	}
	
	@Test
	public void GIVEN_pathFinder_WHEN_IsAskedToResolveDownLinearPathMaze_THEN_MazeIsResolve(){
		//Arrange
	    final String FIRST_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String SECOND_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String THIRD_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String FOURTH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String FIFTH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String SIXTH_ROW =         	"XXXXXXXXXSXXXXXXXXXX";
	    final String SEVENTH_ROW =        	"XXXXXXXXX XXXXXXXXXX";
	    final String EIGHT_ROW =         	"XXXXXXXXX XXXXXXXXXX";
	    final String NINETH_ROW =         	"XXXXXXXXX XXXXXXXXXX";
	    final String TENTH_ROW =         	"XXXXXXXXX XXXXXXXXXX";
	    final String ELEVENTH_ROW =     	"XXXXXXXXX XXXXXXXXXX";
	    final String TWELVETH_ROW =     	"XXXXXXXXX XXXXXXXXXX";
	    final String THIRDTEENTH_ROW =     	"XXXXXXXXX XXXXXXXXXX";
	    final String FOURTEENTH_ROW =     	"XXXXXXXXX XXXXXXXXXX";
	    final String FIFTHEENTH_ROW =     	"XXXXXXXXXEXXXXXXXXXX";
	    final String SIXTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String SEVENTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String EIGHTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String NINETEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String TWENTYTH_ROW =    		"XXXXXXXXXXXXXXXXXXXX";
	
	    final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHT_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRDTEENTH_ROW + FOURTEENTH_ROW + FIFTHEENTH_ROW + SIXTEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;
	
	    IPathFinder pathfinder = new PathFinderCounterClockwise();
	    
    	//Act
	
  		String newMaze = pathfinder.pathToExit(MAZE);
  		
  		//Assert
  		final String EXPECTED_FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SECOND_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_THIRD_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FOURTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FIFTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SIXTH_ROW = 		"XXXXXXXXXSXXXXXXXXXX";
  		final String EXPECTED_SEVENTH_ROW = 	"XXXXXXXXXPXXXXXXXXXX";
  		final String EXPECTED_EIGHTH_ROW = 		"XXXXXXXXXPXXXXXXXXXX";
  		final String EXPECTED_NINETH_ROW = 		"XXXXXXXXXPXXXXXXXXXX";
  		final String EXPECTED_TENTH_ROW = 		"XXXXXXXXXPXXXXXXXXXX";
  		final String EXPECTED_ELEVENTH_ROW = 	"XXXXXXXXXPXXXXXXXXXX";
  		final String EXPECTED_TWELVETH_ROW = 	"XXXXXXXXXPXXXXXXXXXX";
  		final String EXPECTED_THIRTEENTH_ROW = 	"XXXXXXXXXPXXXXXXXXXX";
  		final String EXPECTED_FOURTEENTH_ROW = 	"XXXXXXXXXPXXXXXXXXXX";
  		final String EXPECTED_FIVETEENTH_ROW = 	"XXXXXXXXXEXXXXXXXXXX";
  		final String EXPECTED_SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SEVENTEENTH_ROW = "XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		
  		final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHTH_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIVETEENTH_ROW + EXPECTED_SIXTHEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;
  		final String ACTUAL_MAZE = newMaze;
  		assertEquals(EXPECTED_MAZE,ACTUAL_MAZE);
	}
	
	@Test
	public void GIVEN_pathFinder_WHEN_IsAskedToResolveNonLinearPathMaze_THEN_MazeIsResolve(){
		//Arrange
	    final String FIRST_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String SECOND_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String THIRD_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String FOURTH_ROW =         	"XXXXXXXXX XXXXXXXXXX";
	    final String FIFTH_ROW =         	"XXXXXXXXX XXXXXXXXXX";
	    final String SIXTH_ROW =         	"XXXXXXXXXS  EXXXXXXX";
	    final String SEVENTH_ROW =        	"XXXXXXXXXXXXXXXXXXXX";
	    final String EIGHT_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String NINETH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String TENTH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String ELEVENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String TWELVETH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String THIRDTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String FOURTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String FIFTHEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String SIXTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String SEVENTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String EIGHTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String NINETEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String TWENTYTH_ROW =    		"XXXXXXXXXXXXXXXXXXXX";
	
	    final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHT_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRDTEENTH_ROW + FOURTEENTH_ROW + FIFTHEENTH_ROW + SIXTEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;
	
	    IPathFinder pathfinder = new PathFinderCounterClockwise();
	    
    	//Act
	
  		String newMaze = pathfinder.pathToExit(MAZE);
  		
  		//Assert
  		final String EXPECTED_FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SECOND_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_THIRD_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FOURTH_ROW = 		"XXXXXXXXX XXXXXXXXXX";
  		final String EXPECTED_FIFTH_ROW = 		"XXXXXXXXX XXXXXXXXXX";
  		final String EXPECTED_SIXTH_ROW = 		"XXXXXXXXXSPPEXXXXXXX";
  		final String EXPECTED_SEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_EIGHTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_NINETH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TENTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_ELEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TWELVETH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_THIRTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FOURTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FIVETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SEVENTEENTH_ROW = "XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		
  		final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHTH_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIVETEENTH_ROW + EXPECTED_SIXTHEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;
  		final String ACTUAL_MAZE = newMaze;
  		assertEquals(EXPECTED_MAZE,ACTUAL_MAZE);
	}
	
	@Test
	public void GIVEN_pathFinder_WHEN_IsAskedToResolveComplexNonLinearPathMaze_THEN_MazeIsResolve(){
		//Arrange
	    final String FIRST_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String SECOND_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String THIRD_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String FOURTH_ROW =         	"XXXXXXXXX XXXXXXXXXX";
	    final String FIFTH_ROW =         	"XXXXXXXXX XXXXXXXXXX";
	    final String SIXTH_ROW =         	"XXXXXX   S    XXXXXX";
	    final String SEVENTH_ROW =        	"XXXXXX XXXXXXXXXXXXX";
	    final String EIGHT_ROW =         	"XXXXXX  EXXXXXXXXXXX";
	    final String NINETH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String TENTH_ROW =         	"XXXXXXXXXXXXXXXXXXXX";
	    final String ELEVENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String TWELVETH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String THIRDTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String FOURTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String FIFTHEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String SIXTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String SEVENTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String EIGHTEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String NINETEENTH_ROW =     	"XXXXXXXXXXXXXXXXXXXX";
	    final String TWENTYTH_ROW =    		"XXXXXXXXXXXXXXXXXXXX";
	
	    final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHT_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRDTEENTH_ROW + FOURTEENTH_ROW + FIFTHEENTH_ROW + SIXTEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;
	
	    IPathFinder pathfinder = new PathFinderClockwise();
	    
    	//Act
	
  		String newMaze = pathfinder.pathToExit(MAZE);
  		
  		//Assert
  		final String EXPECTED_FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SECOND_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_THIRD_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FOURTH_ROW = 		"XXXXXXXXX XXXXXXXXXX";
  		final String EXPECTED_FIFTH_ROW = 		"XXXXXXXXX XXXXXXXXXX";
  		final String EXPECTED_SIXTH_ROW = 		"XXXXXXPPPS    XXXXXX";
  		final String EXPECTED_SEVENTH_ROW = 	"XXXXXXPXXXXXXXXXXXXX";
  		final String EXPECTED_EIGHTH_ROW = 		"XXXXXXPPEXXXXXXXXXXX";
  		final String EXPECTED_NINETH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TENTH_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_ELEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TWELVETH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_THIRTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FOURTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_FIVETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_SEVENTEENTH_ROW = "XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		final String EXPECTED_TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
  		
  		final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHTH_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIVETEENTH_ROW + EXPECTED_SIXTHEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;
  		final String ACTUAL_MAZE = newMaze;
  		assertEquals(EXPECTED_MAZE,ACTUAL_MAZE);
	}
	
	@Test
	public void GIVEN_pathFinder_WHEN_IsAskedToResolveEvenMoreComplexNonLinearPathMaze_THEN_MazeIsResolve(){

		  final String FIRST_ROW =             "XXXXXXXXXXXXXXXXXXXX";
	      final String SECOND_ROW =            "XXXXXXXXXXXXXXXXXXXX";
	      final String THIRD_ROW =             "XXXXXXXXXXXXXXXXXXXX";
	      final String FOURTH_ROW =            "XXXXXXXXX XXXXXXXXXX";
	      final String FIFTH_ROW =             "XXXXXXXXX XXXXXXXXXX";
	      final String SIXTH_ROW =             "XXXXXX   S   XXXXXXX";
	      final String SEVENTH_ROW =           "XXXXXX XXXXXXXXXXXXX";
	      final String EIGHT_ROW =             "XXXXXX  XXXXXXXXXXXX";
	      final String NINETH_ROW =            "XXXE   XXXXXXXXXXXXX";
	      final String TENTH_ROW =             "XXXXXX XXXXXXXXXXXXX";
	      final String ELEVENTH_ROW =		   "XXXXXX XXXXXXXXXXXXX";
	      final String TWELVETH_ROW =          "XXXXXXXXXXXXXXXXXXXX";
	      final String THIRDTEENTH_ROW =       "XXXXXXXXXXXXXXXXXXXX";
	      final String FOURTEENTH_ROW =        "XXXXXXXXXXXXXXXXXXXX";
	      final String FIFTHEENTH_ROW =        "XXXXXXXXXXXXXXXXXXXX";
	      final String SIXTEENTH_ROW =         "XXXXXXXXXXXXXXXXXXXX";
	      final String SEVENTEENTH_ROW =       "XXXXXXXXXXXXXXXXXXXX";
	      final String EIGHTEENTH_ROW =        "XXXXXXXXXXXXXXXXXXXX";
	      final String NINETEENTH_ROW =        "XXXXXXXXXXXXXXXXXXXX";
	      final String TWENTYTH_ROW =          "XXXXXXXXXXXXXXXXXXXX";


	  final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHT_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRDTEENTH_ROW + FOURTEENTH_ROW + FIFTHEENTH_ROW + SIXTEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;

	  IPathFinder pathfinder = new PathFinderClockwise();

	  //Act
	  final String ACTUAL_MAZE = pathfinder.pathToExit(MAZE);

	  //Assert
	  	  final String EXPECTED_FIRST_ROW =             "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_SECOND_ROW =            "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_THIRD_ROW =             "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_FOURTH_ROW =            "XXXXXXXXX XXXXXXXXXX";
	      final String EXPECTED_FIFTH_ROW =             "XXXXXXXXX XXXXXXXXXX";
	      final String EXPECTED_SIXTH_ROW =             "XXXXXXPPPS   XXXXXXX";
	      final String EXPECTED_SEVENTH_ROW =           "XXXXXXPXXXXXXXXXXXXX";
	      final String EXPECTED_EIGHT_ROW =             "XXXXXXP XXXXXXXXXXXX";
	      final String EXPECTED_NINETH_ROW =            "XXXEPPPXXXXXXXXXXXXX";
	      final String EXPECTED_TENTH_ROW =             "XXXXXX XXXXXXXXXXXXX";
	      final String EXPECTED_ELEVENTH_ROW =		  	"XXXXXX XXXXXXXXXXXXX";
	      final String EXPECTED_TWELVETH_ROW =          "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_THIRDTEENTH_ROW =       "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_FOURTEENTH_ROW =        "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_FIFTHEENTH_ROW =        "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_SIXTEENTH_ROW =         "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_SEVENTEENTH_ROW =       "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_EIGHTEENTH_ROW =        "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_NINETEENTH_ROW =        "XXXXXXXXXXXXXXXXXXXX";
	      final String EXPECTED_TWENTYTH_ROW =          "XXXXXXXXXXXXXXXXXXXX";

	      final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHT_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRDTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIFTHEENTH_ROW + EXPECTED_SIXTEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;

	  assertEquals(EXPECTED_MAZE, ACTUAL_MAZE);
	}
	
	@Test
	public void GIVEN_pathFinder_WHEN_IsAskedToResolveAMastermindMazeClockwise_THEN_MazeIsResolve(){

		final String FIRST_ROW =             "XXXXXXXXXXXXXXXXXXXX";
        final String SECOND_ROW =            "XS                 X";
        final String THIRD_ROW =             "X XXXXXXXXXXXXXXXXXX";
        final String FOURTH_ROW =            "X         XXXXXXXXXX";
        final String FIFTH_ROW =             "X XXXXXXX XXXX XXXXX";
        final String SIXTH_ROW =             "X XXXXXXX XXXX     X";
        final String SEVENTH_ROW =           "X XX         X XX XX";
        final String EIGHT_ROW =             "X XXXXXXXXXX X  X XX";
        final String NINETH_ROW =            "X       XXXX XX X XX";
        final String TENTH_ROW =             "XXXXX XXXXXX    X XX";
        final String ELEVENTH_ROW =		     "XX    X    X XXXX XX";
        final String TWELVETH_ROW =          "XX XXXX XX XXXXXX XX";
        final String THIRDTEENTH_ROW =       "XX      X          X";
        final String FOURTEENTH_ROW =        "XXXXXXXXXXXXX XXXXXX";
        final String FIFTHEENTH_ROW =        "XXXXXXXXXXXXX     EX";
        final String SIXTEENTH_ROW =         "XXXXXXXXXXXXXXXXXXXX";
        final String SEVENTEENTH_ROW =       "XXXXXXXXXXXXXXXXXX X";
        final String EIGHTEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String NINETEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String TWENTYTH_ROW =          "XXXXXXXXXXXXXXXXXXXX";


		final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHT_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRDTEENTH_ROW + FOURTEENTH_ROW + FIFTHEENTH_ROW + SIXTEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;

		IPathFinder pathfinder = new PathFinderClockwise();

		//Act
		final String ACTUAL_MAZE = pathfinder.pathToExit(MAZE);

		//Assert
		final String EXPECTED_FIRST_ROW =             "XXXXXXXXXXXXXXXXXXXX";
        final String EXPECTED_SECOND_ROW =            "XS                 X";
        final String EXPECTED_THIRD_ROW =             "XPXXXXXXXXXXXXXXXXXX";
        final String EXPECTED_FOURTH_ROW =            "XPPPPPPPPPXXXXXXXXXX";
        final String EXPECTED_FIFTH_ROW =             "X XXXXXXXPXXXX XXXXX";
        final String EXPECTED_SIXTH_ROW =             "X XXXXXXXPXXXXPPPP X";
        final String EXPECTED_SEVENTH_ROW =           "X XX     PPPPXPXXPXX";
        final String EXPECTED_EIGHT_ROW =             "X XXXXXXXXXXPXPPXPXX";
        final String EXPECTED_NINETH_ROW =            "X       XXXXPXXPXPXX";
        final String EXPECTED_TENTH_ROW =             "XXXXX XXXXXXPPPPXPXX";
        final String EXPECTED_ELEVENTH_ROW =		  "XX    X    X XXXXPXX";
        final String EXPECTED_TWELVETH_ROW =          "XX XXXX XX XXXXXXPXX";
        final String EXPECTED_THIRDTEENTH_ROW =       "XX      X    PPPPP X";
        final String EXPECTED_FOURTEENTH_ROW =        "XXXXXXXXXXXXXPXXXXXX";
        final String EXPECTED_FIFTHEENTH_ROW =        "XXXXXXXXXXXXXPPPPPEX";
        final String EXPECTED_SIXTEENTH_ROW =         "XXXXXXXXXXXXXXXXXXXX";
        final String EXPECTED_SEVENTEENTH_ROW =       "XXXXXXXXXXXXXXXXXX X";
        final String EXPECTED_EIGHTEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String EXPECTED_NINETEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String EXPECTED_TWENTYTH_ROW =          "XXXXXXXXXXXXXXXXXXXX";

        final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHT_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRDTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIFTHEENTH_ROW + EXPECTED_SIXTEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;

		assertEquals(EXPECTED_MAZE, ACTUAL_MAZE);
	}
	
	@Test
	public void GIVEN_pathFinderCounterClockwise_WHEN_IsAskedToResolveAMastermindMaze_THEN_MazeIsResolve(){

		final String FIRST_ROW =             "XXXXXXXXXXXXXXXXXXXX";
        final String SECOND_ROW =            "XS                 X";
        final String THIRD_ROW =             "X XXXXXXXXXXXXXXXXXX";
        final String FOURTH_ROW =            "X         XXXXXXXXXX";
        final String FIFTH_ROW =             "X XXXXXXX XXXX XXXXX";
        final String SIXTH_ROW =             "X XXXXXXX XXXX     X";
        final String SEVENTH_ROW =           "X XX         X XX XX";
        final String EIGHT_ROW =             "X XXXXXXXXXX X  X XX";
        final String NINETH_ROW =            "X       XXXX XX X XX";
        final String TENTH_ROW =             "XXXXX XXXXXX    X XX";
        final String ELEVENTH_ROW =		     "XX    X    X XXXX XX";
        final String TWELVETH_ROW =          "XX XXXX XX XXXXXX XX";
        final String THIRDTEENTH_ROW =       "XX      X          X";
        final String FOURTEENTH_ROW =        "XXXXXXXXXXXXX XXXXXX";
        final String FIFTHEENTH_ROW =        "XXXXXXXXXXXXX     EX";
        final String SIXTEENTH_ROW =         "XXXXXXXXXXXXXXXXXXXX";
        final String SEVENTEENTH_ROW =       "XXXXXXXXXXXXXXXXXX X";
        final String EIGHTEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String NINETEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String TWENTYTH_ROW =          "XXXXXXXXXXXXXXXXXXXX";


		final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHT_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRDTEENTH_ROW + FOURTEENTH_ROW + FIFTHEENTH_ROW + SIXTEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;

		IPathFinder pathfinder = new PathFinderCounterClockwise();

		//Act
		final String ACTUAL_MAZE = pathfinder.pathToExit(MAZE);

		//Assert
		final String EXPECTED_FIRST_ROW =             "XXXXXXXXXXXXXXXXXXXX";
        final String EXPECTED_SECOND_ROW =            "XS                 X";
        final String EXPECTED_THIRD_ROW =             "XPXXXXXXXXXXXXXXXXXX";
        final String EXPECTED_FOURTH_ROW =            "XP        XXXXXXXXXX";
        final String EXPECTED_FIFTH_ROW =             "XPXXXXXXX XXXX XXXXX";
        final String EXPECTED_SIXTH_ROW =             "XPXXXXXXX XXXX     X";
        final String EXPECTED_SEVENTH_ROW =           "XPXX         X XX XX";
        final String EXPECTED_EIGHT_ROW =             "XPXXXXXXXXXX X  X XX";
        final String EXPECTED_NINETH_ROW =            "XPPPPP  XXXX XX X XX";
        final String EXPECTED_TENTH_ROW =             "XXXXXPXXXXXX    X XX";
        final String EXPECTED_ELEVENTH_ROW =		  "XXPPPPXPPPPX XXXX XX";
        final String EXPECTED_TWELVETH_ROW =          "XXPXXXXPXXPXXXXXX XX";
        final String EXPECTED_THIRDTEENTH_ROW =       "XXPPPPPPX PPPP     X";
        final String EXPECTED_FOURTEENTH_ROW =        "XXXXXXXXXXXXXPXXXXXX";
        final String EXPECTED_FIFTHEENTH_ROW =        "XXXXXXXXXXXXXPPPPPEX";
        final String EXPECTED_SIXTEENTH_ROW =         "XXXXXXXXXXXXXXXXXXXX";
        final String EXPECTED_SEVENTEENTH_ROW =       "XXXXXXXXXXXXXXXXXX X";
        final String EXPECTED_EIGHTEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String EXPECTED_NINETEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String EXPECTED_TWENTYTH_ROW =          "XXXXXXXXXXXXXXXXXXXX";

        final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHT_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRDTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIFTHEENTH_ROW + EXPECTED_SIXTEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;

		assertEquals(EXPECTED_MAZE, ACTUAL_MAZE);
	}
	
	@Test(expected = UnsolvableMaze.class)
	public void GIVEN_PathFinder_WHEN_IsAskedToResolveAnUnsolvableMaze(){

		final String FIRST_ROW =             "XXXXXXXXXXXXXXXXXXXX";
        final String SECOND_ROW =            "XS                 X";
        final String THIRD_ROW =             "X XXXXXXXXXXXXXXXXXX";
        final String FOURTH_ROW =            "X         XXXXXXXXXX";
        final String FIFTH_ROW =             "X XXXXXXX XXXX XXXXX";
        final String SIXTH_ROW =             "X XXXXXXX XXXX     X";
        final String SEVENTH_ROW =           "X XX         X XX XX";
        final String EIGHT_ROW =             "X XXXXXXXXXX X  X XX";
        final String NINETH_ROW =            "X       XXXX XX X XX";
        final String TENTH_ROW =             "XXXXX XXXXXX    X XX";
        final String ELEVENTH_ROW =		     "XX    X    X XXXX XX";
        final String TWELVETH_ROW =          "XX XXXX XXXXXXXXX XX";
        final String THIRDTEENTH_ROW =       "XX      X          X";
        final String FOURTEENTH_ROW =        "XXXXXXXXXXXXX XXXXXX";
        final String FIFTHEENTH_ROW =        "XXXXXXXXXXXXX    XEX";
        final String SIXTEENTH_ROW =         "XXXXXXXXXXXXXXXXXXXX";
        final String SEVENTEENTH_ROW =       "XXXXXXXXXXXXXXXXXX X";
        final String EIGHTEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String NINETEENTH_ROW =        "XXXXXXXXXXXXXXXXXX X";
        final String TWENTYTH_ROW =          "XXXXXXXXXXXXXXXXXXXX";


		final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHT_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRDTEENTH_ROW + FOURTEENTH_ROW + FIFTHEENTH_ROW + SIXTEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;

		IPathFinder pathfinder = new PathFinderCounterClockwise();

		//Act
		final String ACTUAL_MAZE = pathfinder.pathToExit(MAZE);

	}
	

	@Test
	public void GIVEN_pathFinder_WHEN_IsaskedToResolveLoopLinearPathMaze_THEN_MazeIsResolve() {
		
		//Arrange
		IPathFinder pathfinder = new PathFinderCounterClockwise();
		
		final String FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String SECOND_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String THIRD_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String FOURTH_ROW = 		"XXXXXXXXXXXXXEXXXXXX";
		final String FIFTH_ROW = 		"XXXXXXXXXXXXX XXXXXX";
		final String SIXTH_ROW = 		"XXXXX    S    XXXXXX";
		final String SEVENTH_ROW = 		"XXXXX XXX XXXXXXXXXX";
		final String EIGHTH_ROW = 		"XXXXX XXX  XXXXXXXXX";
		final String NINETH_ROW = 		"XXXXX XXXX XXXXXXXXX";
		final String TENTH_ROW = 		"XXXXX      XXXXXXXXX";
		final String ELEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String TWELVETH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String THIRTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String FOURTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String FIVETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String SEVENTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		
		final String MAZE = FIRST_ROW + SECOND_ROW + THIRD_ROW + FOURTH_ROW + FIFTH_ROW + SIXTH_ROW + SEVENTH_ROW + EIGHTH_ROW + NINETH_ROW + TENTH_ROW + ELEVENTH_ROW + TWELVETH_ROW + THIRTEENTH_ROW + FOURTEENTH_ROW + FIVETEENTH_ROW + SIXTHEENTH_ROW + SEVENTEENTH_ROW + EIGHTEENTH_ROW + NINETEENTH_ROW + TWENTYTH_ROW;  
		
		//Act
		
		String newMaze = pathfinder.pathToExit(MAZE);
		
		//Assert
		final String EXPECTED_FIRST_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SECOND_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_THIRD_ROW = 		"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_FOURTH_ROW = 		"XXXXXXXXXXXXXEXXXXXX";
		final String EXPECTED_FIFTH_ROW = 		"XXXXXXXXXXXXXPXXXXXX";
		final String EXPECTED_SIXTH_ROW = 		"XXXXX    SPPPPXXXXXX";
		final String EXPECTED_SEVENTH_ROW = 	"XXXXX XXX XXXXXXXXXX";
		final String EXPECTED_EIGHTH_ROW = 		"XXXXX XXX  XXXXXXXXX";
		final String EXPECTED_NINETH_ROW = 		"XXXXX XXXX XXXXXXXXX";
		final String EXPECTED_TENTH_ROW = 		"XXXXX      XXXXXXXXX";
		final String EXPECTED_ELEVENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_TWELVETH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_THIRTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_FOURTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_FIVETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SIXTHEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_SEVENTEENTH_ROW = "XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_EIGHTEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_NINETEENTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		final String EXPECTED_TWENTYTH_ROW = 	"XXXXXXXXXXXXXXXXXXXX";
		
		final String EXPECTED_MAZE = EXPECTED_FIRST_ROW + EXPECTED_SECOND_ROW + EXPECTED_THIRD_ROW + EXPECTED_FOURTH_ROW + EXPECTED_FIFTH_ROW + EXPECTED_SIXTH_ROW + EXPECTED_SEVENTH_ROW + EXPECTED_EIGHTH_ROW + EXPECTED_NINETH_ROW + EXPECTED_TENTH_ROW + EXPECTED_ELEVENTH_ROW + EXPECTED_TWELVETH_ROW + EXPECTED_THIRTEENTH_ROW + EXPECTED_FOURTEENTH_ROW + EXPECTED_FIVETEENTH_ROW + EXPECTED_SIXTHEENTH_ROW + EXPECTED_SEVENTEENTH_ROW + EXPECTED_EIGHTEENTH_ROW + EXPECTED_NINETEENTH_ROW + EXPECTED_TWENTYTH_ROW;
		final String ACTUAL_MAZE = newMaze;
		assertEquals(EXPECTED_MAZE,ACTUAL_MAZE);
	}
	
}
